// @vitest-environment jsdom
import { cleanup, fireEvent, render, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { invoke } from "@tauri-apps/api/core";
import { renderAsync } from "docx-preview";
import { DocxPreview, type DocxPreviewProps } from "./DocxPreview";
import type { TaskView } from "./api";
import type { OfficePreview } from "./docx-preview-model";
vi.mock("@tauri-apps/api/core", () => ({ invoke: vi.fn() }));
vi.mock("docx-preview", () => ({ renderAsync: vi.fn() }));
const task: TaskView = {
  meta: {
    id: "task",
    state: "awaiting_review",
    kind: "docx",
    created_at: 1,
    updated_at: 1,
    error: null,
  },
  text: "张三公开",
  entities: [
    {
      id: "entity",
      entity_type: "PERSON",
      type_label: "姓名",
      score: 1,
      source: "test",
      selected: true,
      display: { start: 0, end: 2 },
      text: "张三",
      replacement: null,
      effective_replacement: "某人",
    },
  ],
  regions: [],
  revision: 1,
  extension: "docx",
  preview: null,
  options: { ocr_profile: "mobile", pdf_mode: "safe_rebuild" },
  warnings: [],
};
const meta = (text = "张三公开"): OfficePreview => ({
  revision: 1,
  layout_available: true,
  reason: null,
  anchors: [
    {
      id: "sixa_text_0",
      text,
      display: { start: 0, end: text.length },
      label: "正文",
      available_in_layout: true,
    },
  ],
  images: [{ index: 0, name: "照片", occurrences: ["sixa_image_0_0"] }],
  warnings: [],
});
const props = (): DocxPreviewProps => ({
  task,
  result: false,
  completed: false,
  onFocusEntity: vi.fn(),
  onOpenImage: vi.fn(),
});
beforeEach(() => {
  vi.mocked(invoke).mockReset();
  vi.mocked(renderAsync).mockReset();
  Object.defineProperty(Element.prototype, "scrollIntoView", {
    value: vi.fn(),
    configurable: true,
  });
  Object.defineProperty(URL, "revokeObjectURL", {
    value: vi.fn(),
    configurable: true,
  });
  vi.mocked(invoke).mockImplementation(async (command, args) => {
    const output = (args as { result: boolean }).result;
    return (
      command === "office_preview"
        ? meta(output ? "实际输出" : "张三公开")
        : [output ? 2 : 1]
    ) as never;
  });
  vi.mocked(renderAsync).mockImplementation(async (bytes, body, styles) => {
    const text = (bytes as Uint8Array)[0] === 2 ? "实际输出" : "张三公开";
    body.innerHTML = `<div class="sixa-word-wrapper"><section class="sixa-word"><p><span id="sixa_text_0"></span><b>${text}</b><span id="sixa_image_0_0"></span><img src="blob:owned"></p></section></div>`;
    if (styles)
      styles.innerHTML = "<style>section.sixa-word { width: 794px; }</style>";
    return {};
  });
});
afterEach(() => cleanup());
function shadow(container: HTMLElement) {
  return container.querySelector(".sixa-docx-host")!.shadowRoot!;
}
describe("DOCX preview", () => {
  it("updates draft annotations and undo without parsing the package again", async () => {
    const inputs = props();
    const view = render(<DocxPreview {...inputs} />);
    await waitFor(() =>
      expect(shadow(view.container).querySelector("b")?.textContent).toBe(
        "张三公开",
      ),
    );
    view.rerender(
      <DocxPreview {...inputs} result task={{ ...task, revision: 2 }} />,
    );
    await waitFor(() =>
      expect(shadow(view.container).querySelector("b")?.textContent).toBe(
        "某人公开",
      ),
    );
    view.rerender(
      <DocxPreview
        {...inputs}
        result
        task={{
          ...task,
          revision: 3,
          entities: [{ ...task.entities[0], selected: false }],
        }}
      />,
    );
    await waitFor(() =>
      expect(shadow(view.container).querySelector("b")?.textContent).toBe(
        "张三公开",
      ),
    );
    expect(renderAsync).toHaveBeenCalledTimes(1);
    expect(renderAsync).toHaveBeenCalledWith(
      expect.any(Uint8Array),
      expect.any(HTMLElement),
      expect.any(HTMLElement),
      expect.objectContaining({
        renderAltChunks: false,
        renderChanges: false,
        ignoreFonts: true,
        useBase64URL: false,
      }),
    );
    view.unmount();
    expect(URL.revokeObjectURL).toHaveBeenCalledWith("blob:owned");
  });
  it("shows actual generated bytes and never applies source entity offsets to output", async () => {
    const view = render(<DocxPreview {...props()} result completed />);
    await waitFor(() =>
      expect(shadow(view.container).querySelector("b")?.textContent).toBe(
        "实际输出",
      ),
    );
    expect(shadow(view.container).querySelector("mark")).toBeNull();
    expect(invoke).toHaveBeenCalledWith(
      "office_preview_docx",
      expect.objectContaining({ result: true }),
    );
  });
  it("keeps a failed output read visible with retry instead of loading source bytes", async () => {
    vi.mocked(invoke).mockImplementation(async (command, args) => {
      if (command === "office_preview_docx") throw Error("读取失败");
      return meta(
        (args as { result: boolean }).result ? "实际输出" : "张三公开",
      ) as never;
    });
    const view = render(<DocxPreview {...props()} result completed />);
    await waitFor(() =>
      expect(view.getByRole("alert").textContent).toContain(
        "无法读取已生成的 DOCX",
      ),
    );
    expect(renderAsync).not.toHaveBeenCalled();
    expect(
      vi
        .mocked(invoke)
        .mock.calls.filter(([command]) => command === "office_preview_docx")
        .every(([, args]) => (args as { result: boolean }).result),
    ).toBe(true);
    fireEvent.click(view.getByText("重试结果预览"));
    await waitFor(() =>
      expect(
        vi
          .mocked(invoke)
          .mock.calls.filter(([command]) => command === "office_preview_docx"),
      ).toHaveLength(2),
    );
  });
  it("supports entity and embedded-image focus through rendered bookmarks", async () => {
    const inputs = props();
    const view = render(<DocxPreview {...inputs} />);
    await waitFor(() =>
      expect(shadow(view.container).querySelector("mark")).not.toBeNull(),
    );
    fireEvent.click(shadow(view.container).querySelector("mark")!);
    fireEvent.click(shadow(view.container).querySelector("img")!);
    expect(inputs.onFocusEntity).toHaveBeenCalledWith("entity");
    expect(inputs.onOpenImage).toHaveBeenCalledWith(0);
    expect(view.getByText(/修改会应用到同一图片/)).toBeTruthy();
  });
  it("uses a complete virtual content view when the backend disables layout", async () => {
    const content: OfficePreview = {
      ...meta(),
      layout_available: false,
      reason: "文档超过排版门限",
      anchors: Array.from({ length: 1000 }, (_, index) => ({
        id: `sixa_text_${index}`,
        text: `正文 ${index}`,
        display: { start: index * 10, end: index * 10 + 6 },
        label: `片段 ${index}`,
        available_in_layout: false,
      })),
    };
    vi.mocked(invoke).mockResolvedValue(content);
    const view = render(<DocxPreview {...props()} />);
    await waitFor(() =>
      expect(view.getByLabelText("完整分块内容")).toBeTruthy(),
    );
    expect(
      view.container.querySelectorAll(".sixa-docx-content-row").length,
    ).toBeLessThan(30);
    expect(renderAsync).not.toHaveBeenCalled();
    expect(invoke).not.toHaveBeenCalledWith(
      "office_preview_docx",
      expect.anything(),
    );
  });
  it("accepts toolbar page requests and reports same-page scroll offsets", async () => {
    const inputs = {
      ...props(),
      onPageChange: vi.fn(),
      onScrollAnchor: vi.fn(),
    };
    const metadata = meta();
    metadata.anchors = [0, 1].map((index) => ({
      id: `sixa_text_${index}`,
      text: "张三公开",
      display: { start: index * 4, end: index * 4 + 4 },
      label: "正文",
      available_in_layout: true,
    }));
    vi.mocked(invoke).mockImplementation(
      async (command) =>
        (command === "office_preview" ? metadata : [1]) as never,
    );
    vi.mocked(renderAsync).mockImplementation(async (_, body) => {
      body.innerHTML =
        '<section class="sixa-word" data-page="0"><p><span id="sixa_text_0"></span><b>张三公开</b></p></section><section class="sixa-word" data-page="1"><p><span id="sixa_text_1"></span><b>张三公开</b></p></section>';
      return {};
    });
    const view = render(
      <div className="preview-pane">
        <DocxPreview {...inputs} />
      </div>,
    );
    await waitFor(() =>
      expect(shadow(view.container).querySelectorAll("section")).toHaveLength(
        2,
      ),
    );
    const scroller =
      view.container.querySelector<HTMLElement>(".preview-pane")!;
    const rect = (top: number, height: number) => ({
      top,
      bottom: top + height,
      height,
      left: 0,
      right: 700,
      width: 700,
      x: 0,
      y: top,
      toJSON: () => ({}),
    });
    vi.spyOn(scroller, "getBoundingClientRect").mockImplementation(() =>
      rect(0, 600),
    );
    shadow(view.container)
      .querySelectorAll<HTMLElement>("section")
      .forEach((page, index) => {
        vi.spyOn(page, "getBoundingClientRect").mockImplementation(() =>
          rect(8 + index * 900 - scroller.scrollTop, 850),
        );
        vi.spyOn(
          page.querySelector<HTMLElement>("[id]")!,
          "getBoundingClientRect",
        ).mockImplementation(() =>
          rect(8 + index * 900 - scroller.scrollTop, 20),
        );
      });
    view.rerender(
      <div className="preview-pane">
        <DocxPreview {...inputs} pageRequest={{ page: 1, token: 1 }} />
      </div>,
    );
    await waitFor(() => expect(scroller.scrollTop).toBe(900));
    expect(inputs.onPageChange).toHaveBeenCalledWith(1);
    scroller.scrollTop = 970;
    fireEvent.scroll(scroller);
    await waitFor(() =>
      expect(inputs.onScrollAnchor).toHaveBeenCalledWith(
        expect.objectContaining({
          anchorId: "sixa_text_1",
          page: 1,
          offset: 70,
          fraction: expect.any(Number),
        }),
      ),
    );
    const count = inputs.onScrollAnchor.mock.calls.length;
    view.rerender(
      <div className="preview-pane">
        <DocxPreview
          {...inputs}
          pageRequest={{ page: 1, token: 1 }}
          scrollAnchor={{ anchorId: "sixa_text_1", page: 1, fraction: 0.5 }}
        />
      </div>,
    );
    fireEvent.scroll(scroller);
    await new Promise((resolve) => setTimeout(resolve, 25));
    expect(inputs.onScrollAnchor).toHaveBeenCalledTimes(count);
  });
});
