"""Real Office/PDF/image regression fixtures.

These tests deliberately build files with the same libraries used by the
application.  They exercise the binary adapters without downloading optional
NER/OCR models, and keep all generated bytes in memory.
"""

from __future__ import annotations

import io
import zipfile

import fitz
import pytest
from docx import Document
from docx.opc.constants import RELATIONSHIP_TYPE
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import RGBColor
from openpyxl import Workbook, load_workbook
from openpyxl.comments import Comment
from openpyxl.workbook.defined_name import DefinedName
from PIL import Image, ImageChops, ImageDraw, ImageFont

from app.file_handlers import (
    _redact_image,
    _redact_pdf,
    _replace_docx_text,
    _replace_xlsx,
    extract_text,
)


def _entity(text: str, start: int, *, kind: str = "PHONE", selected: bool = True, **extra) -> dict:
    return {"type": kind, "text": text, "start": start, "end": start + len(text), "selected": selected, **extra}


def test_docx_cross_run_selection_preserves_format_and_duplicate_occurrence() -> None:
    document = Document()
    paragraph = document.add_paragraph()
    first = paragraph.add_run("客户 ")
    first.bold = True
    middle = paragraph.add_run("13800")
    middle.italic = True
    # The reviewed value intentionally crosses the run boundary (5 + 6
    # characters) while the rest of the paragraph remains separately styled.
    last = paragraph.add_run("138000 结束")
    last.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
    document.add_paragraph("重复 13800138000 与 13800138000")
    # Add a real hyperlink run; python-docx intentionally omits it from
    # ``Paragraph.runs``, so the adapter must traverse XML descendants.
    linked = document.add_paragraph("链接 ")
    rel_id = linked.part.relate_to("https://example.test/13800138000", RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), rel_id)
    linked_run = OxmlElement("w:r")
    linked_text = OxmlElement("w:t")
    linked_text.text = "13800138000"
    linked_run.append(linked_text)
    hyperlink.append(linked_run)
    linked._p.append(hyperlink)
    source = io.BytesIO()
    document.save(source)
    raw = source.getvalue()
    text = extract_text(raw, "fixture.docx")

    # Select only the first occurrence in the first paragraph.  The second
    # equal value is deliberately left untouched to verify offset semantics.
    start = text.index("13800138000")
    masked = _replace_docx_text(raw, [_entity("13800138000", start)], None)
    result = Document(io.BytesIO(masked))
    assert result.paragraphs[0].text == "客户 138****8000 结束"
    assert result.paragraphs[1].text == "重复 13800138000 与 13800138000"
    runs = result.paragraphs[0].runs
    assert runs[0].text == "客户 " and runs[0].bold is True
    assert any(run.italic for run in runs)
    assert any(run.font.color and run.font.color.rgb == RGBColor(0xCC, 0x00, 0x00) for run in runs)
    link_start = text.rindex("13800138000")
    linked_masked = _replace_docx_text(raw, [_entity("13800138000", link_start)], None)
    linked_result = Document(io.BytesIO(linked_masked))
    assert "138****8000" in linked_result.paragraphs[2].text


def test_docx_linked_header_and_footer_offsets_are_resolved() -> None:
    document = Document()
    document.add_section()
    document.sections[0].header.paragraphs[0].text = "页眉 13800138000"
    document.sections[0].footer.paragraphs[0].text = "页脚 13800138000"
    document.sections[1].header.paragraphs[0].text = "页眉 13800138000"
    document.sections[1].footer.paragraphs[0].text = "页脚 13800138000"
    source = io.BytesIO()
    document.save(source)
    raw = source.getvalue()
    text = extract_text(raw, "headers.docx")
    # The selected occurrence is in the second section footer.  Both linked
    # footer renderings share XML and should be removed together.
    start = text.rindex("13800138000")
    masked = _replace_docx_text(raw, [_entity("13800138000", start)], None)
    result_text = extract_text(masked, "headers.docx")
    assert result_text.count("13800138000") == 2  # only headers remain
    assert result_text.count("138****8000") == 2


def test_docx_custom_rule_replacement_is_applied_at_reviewed_offset() -> None:
    document = Document()
    document.add_paragraph("项目 Project-LOCAL 已通过")
    source = io.BytesIO()
    document.save(source)
    raw = source.getvalue()
    text = extract_text(raw, "custom.docx")
    start = text.index("Project-LOCAL")
    entity = _entity(
        "Project-LOCAL",
        start,
        kind="PROJECT_FIXTURE",
        source="custom",
        replacement="[项目]",
    )
    masked = _replace_docx_text(raw, [entity], None)
    assert "Project-LOCAL" not in extract_text(masked, "custom.docx")
    assert "[项目]" in extract_text(masked, "custom.docx")


def test_docx_masks_comment_and_external_hyperlink_target() -> None:
    document = Document()
    anchor = document.add_paragraph("批注锚点")
    document.add_comment(anchor.runs[0], text="联系电话 13800138000", author="fixture")
    linked = document.add_paragraph("客户链接")
    relation_id = linked.part.relate_to(
        "https://example.test/customer/13800138000",
        RELATIONSHIP_TYPE.HYPERLINK,
        is_external=True,
    )
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), relation_id)
    hyperlink_run = OxmlElement("w:r")
    hyperlink_text = OxmlElement("w:t")
    hyperlink_text.text = "查看资料"
    hyperlink_run.append(hyperlink_text)
    hyperlink.append(hyperlink_run)
    linked._p.append(hyperlink)
    source = io.BytesIO()
    document.save(source)
    raw = source.getvalue()
    text = extract_text(raw, "hidden.docx")
    entities = []
    cursor = 0
    while True:
        start = text.find("13800138000", cursor)
        if start < 0:
            break
        entities.append(_entity("13800138000", start))
        cursor = start + 11
    assert len(entities) == 2

    masked = _replace_docx_text(raw, entities, None)
    assert "13800138000" not in extract_text(masked, "hidden.docx")
    with zipfile.ZipFile(io.BytesIO(masked)) as archive:
        assert b"13800138000" not in archive.read("word/comments.xml")
        assert b"13800138000" not in archive.read("word/_rels/document.xml.rels")


def test_xlsx_custom_rule_replacement_is_applied_to_cell_comment_and_url() -> None:
    workbook = Workbook()
    sheet = workbook.active
    sheet["A1"] = "Project-LOCAL"
    sheet["B1"] = "备注 Project-LOCAL"
    sheet["B1"].comment = Comment("Project-LOCAL", "fixture")
    sheet["C1"].hyperlink = "https://example.test/Project-LOCAL"
    source = io.BytesIO()
    workbook.save(source)
    raw = source.getvalue()
    text = extract_text(raw, "custom.xlsx")
    entities = []
    cursor = 0
    while True:
        start = text.find("Project-LOCAL", cursor)
        if start < 0:
            break
        entities.append(
            _entity(
                "Project-LOCAL",
                start,
                kind="PROJECT_FIXTURE",
                source="custom",
                replacement="[项目]",
            )
        )
        cursor = start + len("Project-LOCAL")
    masked = _replace_xlsx(raw, entities, None, "custom.xlsx")
    result = load_workbook(io.BytesIO(masked), data_only=False, keep_links=True)
    assert result.active["A1"].value == "[项目]"
    assert result.active["B1"].value == "备注 [项目]"
    assert result.active["B1"].comment.text == "[项目]"
    assert result.active["C1"].hyperlink.target == "https://example.test/[项目]"


def test_xlsx_replaces_all_reviewed_occurrences_and_preserves_formula_and_vba() -> None:
    workbook = Workbook()
    visible = workbook.active
    visible.title = "Visible"
    hidden = workbook.create_sheet("Hidden")
    hidden.sheet_state = "hidden"
    visible["A1"] = "13800138000 and 13800138000"
    visible["B1"] = '=IF(A1="13800138000","13800138000","ok")'
    visible["C1"] = "safe"
    visible["C1"].comment = Comment("电话 13800138000", "fixture")
    visible["D1"].hyperlink = "https://example.test/13800138000"
    hidden["A1"] = "身份证 11010519491231002X"
    source = io.BytesIO()
    workbook.save(source)
    raw = source.getvalue()
    text = extract_text(raw, "fixture.xlsx")
    entities = []
    cursor = 0
    while True:
        start = text.find("13800138000", cursor)
        if start < 0:
            break
        entities.append(_entity("13800138000", start))
        cursor = start + len("13800138000")
    # Include the comment and URL occurrence as separate reviewed spans.
    masked = _replace_xlsx(raw, entities, None, "fixture.xlsx")
    result = load_workbook(io.BytesIO(masked), data_only=False, keep_links=True)
    assert result["Visible"]["A1"].value == "138****8000 and 138****8000"
    # Formula literals are part of the workbook's persisted content.  Masking
    # them preserves a valid formula while preventing hidden residual values.
    assert result["Visible"]["B1"].value == '=IF(A1="138****8000","138****8000","ok")'
    assert "13800138000" not in result["Visible"]["C1"].comment.text
    assert "13800138000" not in result["Visible"]["D1"].hyperlink.target
    assert result["Hidden"].sheet_state == "hidden"


def test_xlsx_masks_sheet_title_defined_names_and_formula_references() -> None:
    workbook = Workbook()
    sensitive_title = "客户13800138000"
    sheet = workbook.active
    sheet.title = sensitive_title
    sheet["A1"] = "safe"
    sheet["B1"] = f"='{sensitive_title}'!A1"
    workbook.defined_names.add(
        DefinedName("Phone13800138000", attr_text=f"'{sensitive_title}'!$A$1")
    )
    source = io.BytesIO()
    workbook.save(source)
    raw = source.getvalue()
    text = extract_text(raw, "hidden.xlsx")
    entities = []
    cursor = 0
    while True:
        start = text.find("13800138000", cursor)
        if start < 0:
            break
        entities.append(_entity("13800138000", start))
        cursor = start + 11
    assert len(entities) >= 4

    masked = _replace_xlsx(raw, entities, None, "hidden.xlsx")
    result = load_workbook(io.BytesIO(masked), data_only=False, keep_links=True)
    title = result.active.title
    assert title == "客户138____8000"
    assert result.active["B1"].value == "='客户138____8000'!A1"
    assert "Phone138____8000" in result.defined_names
    assert result.defined_names["Phone138____8000"].attr_text == "'客户138____8000'!$A$1"
    with zipfile.ZipFile(io.BytesIO(masked)) as archive:
        assert b"13800138000" not in archive.read("xl/workbook.xml")


def test_xlsm_vba_package_is_retained_when_masking() -> None:
    workbook = Workbook()
    workbook.active["A1"] = "13800138000"
    source = io.BytesIO()
    workbook.save(source)
    original = source.getvalue()
    # A minimal valid-looking VBA package is enough to verify openpyxl's
    # keep_vba round-trip; it is never executed by the test or application.
    rewritten = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(original), "r") as source_zip, zipfile.ZipFile(rewritten, "w", zipfile.ZIP_DEFLATED) as target_zip:
        for info in source_zip.infolist():
            target_zip.writestr(info, source_zip.read(info.filename))
        target_zip.writestr("xl/vbaProject.bin", b"fixture-vba-payload")
    raw = rewritten.getvalue()
    text = extract_text(raw, "fixture.xlsm")
    masked = _replace_xlsx(raw, [_entity("13800138000", text.index("13800138000"))], None, "fixture.xlsm")
    with zipfile.ZipFile(io.BytesIO(masked)) as archive:
        assert archive.read("xl/vbaProject.bin") == b"fixture-vba-payload"
    result = load_workbook(io.BytesIO(masked), keep_vba=True, data_only=False)
    try:
        assert result.active["A1"].value == "138****8000"
    finally:
        if getattr(result, "vba_archive", None) is not None:
            result.vba_archive.close()


def test_pdf_masks_entities_on_their_actual_pages_and_removes_text_layer() -> None:
    document = fitz.open()
    first = document.new_page()
    first.insert_text((72, 72), "电话 13800138000")
    second = document.new_page()
    second.insert_text((72, 72), "邮箱 a@test.com")
    raw = document.tobytes()
    text = extract_text(raw, "fixture.pdf")
    entities = [
        _entity("13800138000", text.index("13800138000")),
        _entity("a@test.com", text.index("a@test.com"), kind="EMAIL"),
    ]
    masked = _redact_pdf(raw, entities, None)
    result = fitz.open(stream=masked, filetype="pdf")
    result_text = "\n".join(page.get_text() for page in result)
    assert "13800138000" not in result_text
    assert "a@test.com" not in result_text
    assert "138****8000" in result_text
    assert "***@***" in result_text
    assert result.page_count == 2


def test_pdf_masks_sensitive_uri_annotations_and_metadata() -> None:
    document = fitz.open()
    page = document.new_page()
    page.insert_text((72, 72), "public text")
    page.insert_link({
        "kind": fitz.LINK_URI,
        "from": fitz.Rect(60, 50, 180, 80),
        "uri": "https://example.test/13800138000?email=a@test.com",
    })
    document.set_metadata({"author": "13800138000"})
    raw = document.tobytes()
    document.close()

    masked = _redact_pdf(raw, [], None)
    result = fitz.open(stream=masked, filetype="pdf")
    links = result[0].get_links()
    assert len(links) == 1
    assert links[0]["uri"] == "https://example.test/138****8000?email=***@***"
    assert not result.metadata.get("author")
    result.close()
    assert b"13800138000" not in masked
    assert b"a@test.com" not in masked


@pytest.mark.parametrize("fmt,extension", [("PNG", "png"), ("JPEG", "jpg"), ("BMP", "bmp"), ("TIFF", "tiff")])
def test_image_outputs_keep_requested_format_and_change_selected_region(fmt: str, extension: str) -> None:
    image = Image.new("RGB", (120, 80), "white")
    ImageDraw.Draw(image).rectangle((20, 10, 80, 60), fill="black")
    source = io.BytesIO()
    image.save(source, format=fmt)
    raw = source.getvalue()
    masked = _redact_image(
        raw,
        [],
        f"fixture.{extension}",
        {"DEFAULT": {"image_action": "solid", "color": "#ff0000"}},
        [{"x": 20 / 120, "y": 10 / 80, "width": 60 / 120, "height": 50 / 80, "selected": True}],
    )
    result = Image.open(io.BytesIO(masked))
    assert result.format == fmt
    assert ImageChops.difference(image.convert("RGB"), result.convert("RGB")).getbbox() is not None
    pixel = result.getpixel((40, 30))[:3]
    if fmt == "JPEG":
        assert pixel[0] > 220 and pixel[1] < 30 and pixel[2] < 30
    else:
        assert pixel == (255, 0, 0)


def test_image_keep_policy_does_not_modify_region() -> None:
    image = Image.new("RGB", (20, 20), "white")
    source = io.BytesIO()
    image.save(source, format="PNG")
    raw = source.getvalue()
    masked = _redact_image(raw, [], "fixture.png", {"DEFAULT": {"image_action": "keep"}}, [{"x": 0, "y": 0, "width": 0.5, "height": 0.5}])
    assert ImageChops.difference(image, Image.open(io.BytesIO(masked)).convert("RGB")).getbbox() is None


def test_image_entity_replacement_is_local_and_uses_text_policy() -> None:
    image = Image.new("RGB", (420, 90), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(r"C:\Windows\Fonts\msyh.ttc", 28)
    draw.text((12, 28), "联系电话：13800138000", font=font, fill="black")
    source = io.BytesIO(); image.save(source, "PNG")
    masked = _redact_image(
        source.getvalue(),
        [{"type": "PHONE", "text": "13800138000", "start": 6, "end": 17,
          "bbox": {"x": 0.43, "y": 0.25, "width": 0.42, "height": 0.42}, "selected": True}],
        "fixture.png", {}, [],
    )
    result = Image.open(io.BytesIO(masked)).convert("RGB")
    # The replacement must be visible in the sensitive region while the far
    # left, non-sensitive label remains pixel-identical.
    assert ImageChops.difference(image.crop((0, 0, 150, 90)), result.crop((0, 0, 150, 90))).getbbox() is None
    assert ImageChops.difference(image.crop((175, 15, 390, 80)), result.crop((175, 15, 390, 80))).getbbox() is not None
